# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Leonard Persson Norblad
title: MSs in Statistics and Machine Learning
email: leonard.norblad@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  leonnorblad
linkedin_username: leonardnorblad
orcid_username: 0009-0004-8562-4118

additional_links:
- title: Kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/leonnorblad

#### About Section ###
about_title: About Me
about_profile_image: images/profilepic.jpg
about_content: | # this will include new lines to allow paragraphs
  Last year Master's student in Statistics and Machine Learning.
  Eager to follow the advancements of AI/ML and find new possibilities to leverage this new technology.
  Currently working on my master's thesis at the Research Institutes of Sweden (RISE).
  Once my thesis is completed in June, I am interested in a full-time employment in AI/ML, preferably in Stockholm.
  
  Hit me up if you are looking for:
  - An awesome colleague to join your team 🌟
  - A collaborator on a ML project🤝

  Or just want to chat about AI/ML in general💡

### Current projects section ###
content:
  - title: Current projects
    layout: list
    content:
      - layout: top-middle
        title: Master thesis at RISE
        description: |
          I am currently working on my master's thesis at the Research Institutes of Sweden.
          My thesis is a part of the EU project *Circular and Sustainable Textile and Clothing* <a href="https://cisutac.eu" target="_blank">cisutac.eu</a>.
          Which is a large initiative to increase textile circularity in Europe.
          More specifically, my thesis aims to automate the sorting process.
          By using machine vision, I am developing a damage detection model to gain a better understanding of the condition of the garment.
          This information is essential for a sorting decision.

### Projects section ####
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Claim Verification Using Generated Data by ChatGPT and Wikipedia
        link: github.com/Leonnorblad/fact-verification
        description: | # this will include new lines to allow paragraphs
          As a part of the LiU text-mining course, I decided to dive deeper in the task of fact verification.
          The model I developed analyzes a user input string and predicts its truthfulness. This is performed by
          comparing the input string to a paragapth of evidence. To extract claims and evidence to train the model I
          scraped wikipedia pages and then fed the articles together with instructions to generate a claim to ChatGPT
          with the help of OpenAIs API. I then enbedded the claims and evidence using BERT and trained the classification network.
          Code and pdf report is available on my GitHub.

      - layout: top-middle
        title: R Package - SeqAlignR
        link: cran.r-project.org/web/packages/SeqAlignR
        #link: github.com/Leonnorblad/SeqAlignR
        additional_links:
          - title: Github
            icon: fab fa-github
            url: github.com/Leonnorblad/SeqAlignR
        description: |
         As a part of the LiU course Bioinformatics (732A51), I developed an R package for sequence alignment and visualization.
         The package uses the Needleman-Wunsch algorithm to align sequences and also provides the option to visualize the alignment
         in a matrix plot with arrows illustrating the paths and scores of different alignments.
         The package is available on CRAN and can be installed to R simply by running `install.packages("SeqAlignR")`.

      - layout: top-middle
        title: LLM - detect AI generated text
        link: kaggle.com/competitions/llm-detect-ai-generated-text
        description: |
          Competition hosted by Kaggle.
          The task was to identify which essay was written by a large language model.
          Together with my two teammates [Elias] and [Filip] we developed an ensemble model consisting of Multinomial Naive Bayes,
          Stochastic Gradient Descent (with modified Huber loss), LightGBM (gradient boosting model), and CatBoost (gradient boosting on decision trees).
          A key aspect of our solution, except the use of an ensemble model, was to use a large ngram in our vectorization of the text.
          Our final submission reached a private LB AUC score of 0.893, giving us a top 36% placement.


#### Experience Section ###
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microtec
        #link: https://microtec.eu/sv-se
        link_text: microtec.eu/sv-se
        sub_title: AI Intern
        caption: January 2023 - August 2023
        description: |
          Microtec developes intellegent wood scanners all over the world.
          As a member of the AI team, my responsibilities included the development and implementation of machine learning solutions
          to extend the functionality of the wood scanners. I worked 8-10 hours per week during my studies and full-time during the summer.

### Education Section ###
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Linköping University
        caption: 2019 - 2022
        sub_title: BSc Statistics and Data Analysis
        description: |
          Earned both practical and theoretical knowledge in statistics and data analysis.
      - layout: left
        title: Linköping University
        caption: 2022 - 2024
        sub_title: MSc Statistics and Machine Learning
        description: |
          I am currently studying statistics and machine learning at Linköping University.

### My interests Section ###
#  - title: My skills
#    layout: text
#    content: |
#      I have expecience of working with a wide range of data types and models.
#
#      ## Programming languages
#       - Python
#       - R
#       - SQL
#       - SAS
#
#      ## Tools
#       - Git
#       - MiniTab
#       - SPSS
#       - Excel
#
#      ## Statistics and Machine learning methods
#      - Neural networks
#      - Convolutional neural networks
#      - Recurrent neural networks
#      - Transformers
#      - Tree based models such as Random forest, XGBoost and AdaBoost
#      - Support vector machines
#      - Clustering nethods such as K-means, DBSCAN and Hierarchical clustering
#      - Dimensionality reduction methods such as PCA, t-SNE and UMAP
#      - Time series analysis such as ARIMA, SARIMA, VAR and VECM
#      - Survival analysis
#      - Bayesian statistics methods such as MCMC, Gibbs sampling
#      - Hypothesis testing such as t-test, chi-squared test, ANOVA
#      - Regression analysis such as linear regression and logistic regression

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
