# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Leonard Persson Norblad
title: AI Engineer @ Predli Consulting
email: leonard.norblad@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  leonnorblad
linkedin_username: leonardpn
#orcid_username: 0009-0004-8562-4118

additional_links:
- title: Kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/leonnorblad

#### About Section ###
about_title: About Me
about_profile_image: images/profilepic.jpg
about_content: |
  Hi, my name is Leonard and I work as an AI Consultant at <a href="https://www.predli.com/" target="_blank">Predli</a>.
  
  🔬 I use statistics, machine learning, and generative AI to solve problems in innovative ways.
  
  🤔 I don't think the latest LLM is the perfect solution for any problem.
  
  👥 I thrive in collaborative environments and prefer to succeed as part of a team rather than alone.
  
  🤝 I value the relations with my clients and colleagues higher than to be the top performer.

  🚀 I love to explore the latest tech.
  

### Current projects section ###
content:
### Projects section ####
  - title: Hobby projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Tell Me When
        sub_title: "Telegram bot for schredruled web agent searches | June - August 2025"
        additional_links:
          - title: Telegram
            icon: fab fa-telegram
            url: https://t.me/TheTellMeWhenBot
        description: |
          Telegram bot that helps you track events and claims over time.
          Simply define a statement e.g., *"Company X has released Product Y"*, and the bot will automatically monitor the web on a fixed schedule.
          When it finds credible sources confirming your statement, it notifies you directly in Telegram with links to those sources.
          You can add, review, or delete statements directly in the chat, making it easy to keep track.
          The bot is live and you can try it by clicking the telegram logo above.

      - layout: top-middle
        title: Laga Billigt
        sub_title: "Autonomous AI-powered Instagram page | March - June 2025"
        additional_links:
          - title: Instagram
            icon: fab fa-instagram
            url: https://www.instagram.com/lagabilligt
        description: |
          Developed an autonomous system that creates and publishes weekly cooking inspiration on Instagram based on Hemköp’s current offers.
          The pipeline retrieves the weekly deals from the website, converts and parses them into structured data, and stores them in an SQL database.
          An LLM filters and ranks the offers, generates recipes and captions, and uses a text-to-image model to produce corresponding dish images.
          All assets are compiled into a carousel post and automatically published via the Instagram API.
      
      - layout: top-middle
        title: Competence Matching
        sub_title: "AI-driven job matching system | Dec 2024 - Feb 2025"
        additional_links:
          - title: Github
            icon: fab fa-github
            url: github.com/Leonnorblad/CompetenceMatching
        description: |
          Developed a lightweight job matching system that runs entirely on your local machine using small open-source LLMs.
          The system helps match your resume with relevant job listings by combining structured metadata filtering with semantic search.
          
          **How it works:** Pre-defined tags are extracted from each job listing and saved as metadata for each chunk in the vector database. During matching, an LLM converts the user’s requirements into a search query to find relevant job listings. An ideal job listing is then generated and used for semantic similarity to identify the most relevant matches.
          
          The 3 steps of the TUI:
          - Email Collection: Create a vector database of job listings with extracted metadata
          - Resume Upload: Parses and summarizes your resume section by section
          - Requirements Matching: Uses an LLM to generate an ideal job listing based on your profile and preferences, then finds matches using semantic similarity

          All processing runs locally without requiring API calls, making it both private and cost-effective. The system uses Llama, Chroma, Langchain, and other open-source tools to deliver efficient matching results.

      - layout: top-middle
        title: Project kickstarter
        sub_title: "Kaggle competition | Oct 2024 - Dec 2024"
        additional_links:
          - title: Kaggle
            icon: fab fa-kaggle
            url: https://www.kaggle.com/competitions/gemini-long-context
        description: |
          In this Kaggle competition, I developed an application to help developers kickstart new projects by utilizing a long-context window with Gemini
          
          **How it works:** You provide a brief project description, and the system analyzes your GitHub profile while gathering relevant resources from GitHub, arXiv, and YouTube. It identifies your skills, finds similar projects, and generates a personalized roadmap with actionable steps to get you started.
          This approach eliminates the need for tedious research, allowing you to dive straight into building.

      - layout: top-middle
        title: Stop Sign Violation Detection
        sub_title: "Computer vision system | June 2024 - Aug 2024"
        additional_links:
          - title: Github
            icon: fab fa-github
            url: github.com/Leonnorblad/DetStopViolation
        description: |
          Developed a computer vision system to detect vehicles violating stop signs using video game data.
          I used YOLOv8 and a fine-tuned Roboflow model to monitor vehicle behavior within defined zones.
          Violations are flagged and video evidence is recorded for review.
          The system tracks all vehicles in the frame and monitors the speed of the vehicle when the front wheel is close to the white line. By analyzing the speed, the system can determine if the vehicle is violating the stop sign or not.
        
          Robloflow requested a blog post on this project which I wrote and published on [Roboflow](https://blog.roboflow.com/stop-sign-violation-detection/).

          The GitHub repository has [![GitHub stars](https://img.shields.io/github/stars/Leonnorblad/DetStopViolation?style=social&label=Stars)](https://github.com/Leonnorblad/DetStopViolation)

      - layout: top-middle
        title: Claim Verification
        sub_title: "Using Generated Data by ChatGPT and Wikipedia | Dec 2023 - Jan 2024"
        #link: github.com/Leonnorblad/fact-verification
        additional_links:
          - title: Github
            icon: fab fa-github
            url: github.com/Leonnorblad/fact-verification
        description: |
          As a part of the LiU text-mining 732A81 course, I decided to dive deeper into the task of fact verification.
          The model I developed analyzes a user input string and predicts it's truthfulness. This is performed by
          comparing the input string to a paragraph of evidence. To extract claims and evidence to train the model I
          scraped Wikipedia pages and then fed the articles together with instructions to generate a claim to ChatGPT
          with the help of OpenAIs API. I then embedded the claims and evidence using BERT and trained the classification network.
          Code and pdf report is available on my GitHub.

      - layout: top-middle
        title: Predict student performance from gameplay
        sub_title: "Kaggle competition | Feb 2023 - Jun 2023"
        additional_links:
          - title: Kaggle
            icon: fab fa-kaggle
            url: kaggle.com/competitions/predict-student-performance-from-game-play
        description: |
          Competition hosted by Kaggle.
          The task was to predict the future performance based on a student's gameplay in an educational game.
          According to our review of the game, the player must pay attention at specific points to answer the questions correctly.
          Because of this, me and my teammate <a href="https://www.linkedin.com/in/elias-forsblom/" target="_blank">Elias Forsblom</a> decided to base our features on the number of clicks and time spent in different rooms in the game.
          In total, the player had to answer 18 different questions at three different levels.
          We leveraged XGBoost's capability of ranking features by importance to find a subset of relevant features for each of the 18 questions.
          We then fitted both a neural network and an XGBoost model on the selected features.
          This was a great learning experience as it was our first time attending a competition on Kaggle.
          Our solution was novel but unfortunately did not perform well in the competition, leaving us on a top 61% placement.

  - title: University projects
    layout: list
    content:
      - layout: top-middle
        title: Master thesis at RISE
        sub_title: "Damage detection in circular fashion | Jan 2024 - May 2024"
        description: |
          During the spring of 2024, I completed my master's thesis at the Research Institutes of Sweden (<a href="https://ri.se" target="_blank">ri.se</a>).
          My thesis was part of the EU project Circular and Sustainable Textile and Clothing (<a href="https://cisutac.eu" target="_blank">cisutac.eu</a>), a major initiative aimed at increasing textile circularity across Europe.

          The focus of my thesis was developing a computer vision model to support automatic sorting decisions in the textile recycling process.
          The model captured images of garments laid flat on a table and accurately detected defects, such as holes and stains.
          These detections serve as a critical input for guiding sorting decisions, helping to improve the efficiency and sustainability of textile recycling.

          Try my model on <a href="https://huggingface.co/spaces/Leonnorblad/FashionDamageDetection" target="_blank">Huggingface</a> 🤗

      - layout: top-middle
        title: LLM - detect AI generated text
        sub_title: "Kaggle competition | Nov 2023 - Jan 2024"
        #link: kaggle.com/competitions/llm-detect-ai-generated-text
        additional_links:
          - title: Kaggle
            icon: fab fa-kaggle
            url: kaggle.com/competitions/llm-detect-ai-generated-text
        description: |
          Competition hosted by Kaggle.
          The task was to distinguish between essays written by a large language model and essays written by a human.
          Together with my two teammates <a href="https://www.linkedin.com/in/elias-forsblom/" target="_blank">Elias Forsblom</a> and <a href="https://www.linkedin.com/in/filip-furuhed" target="_blank"> Filip Furuhed</a>  we developed an ensemble model consisting of Multinomial Naive Bayes,
          Stochastic Gradient Descent (with modified Huber loss), LightGBM (gradient boosting model), and CatBoost (gradient boosting on decision trees).
          A key aspect of our solution, except the use of an ensemble model, was to use a large ngram in our vectorization of the text.
          Our final submission reached a private LB AUC score of 0.893, giving us a top 36% placement.

      - layout: top-middle
        title: R Package - SeqAlignR
        sub_title: "Sequence alignment and visualization tool | Nov 2023 - Dec 2023"
        link: cran.r-project.org/web/packages/SeqAlignR
        #link: github.com/Leonnorblad/SeqAlignR
        additional_links:
          - title: Github
            icon: fab fa-github
            url: github.com/Leonnorblad/SeqAlignR
        description: |
         As a part of the LiU course Bioinformatics 732A51, I developed an R package for sequence alignment and visualization.
         The package uses the Needleman-Wunsch algorithm to align biological sequences such as protein or nucleotide sequences.
         It also provides the option to visualize the alignment in a matrix plot with arrows illustrating the paths and scores of different alignments.
         The package is available on CRAN and can be installed to R simply by running `install.packages("SeqAlignR")`.

         The package current has: [![](https://cranlogs.r-pkg.org/badges/grand-total/SeqAlignR?color=brightgreen)](https://cran.r-project.org/package=SeqAlignR)! 🚀

      - layout: top-middle
        title: Bachelor thesis at Atrium Ljungberg
        sub_title: "Forecasting service matters | Jan 2022 - Jun 2022"
        #link: https://github.com/Leonnorblad/Kandidatuppsats
        additional_links:
          - title: Github
            icon: fab fa-github
            url: github.com/Leonnorblad/Kandidatuppsats
        description: |
         Me and my partner <a href="https://www.linkedin.com/in/roosisabella" target="_blank">Isabella Roos</a> developed forecasting models predicting service matters for the properties at <a href="https://www.al.se/" target="_blank">Atrium Ljungberg</a>.
         The forecasts can be used to make data-driven staff schedule decisions.
         By adjusting the staffing plan to the volume of service matters both overstaffing and understaffing can be avoided.
         This benefits employees, the company, and enhances the overall customer experience.
         The most successful strategy was found to model each area separately.
         Traditional statistical time-series modeling, dynamic regression models, and machine learning methods were explored.
         Summary, code, and full pdf (abstract in English) are available on my GitHub.

#### Experience Section ###
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microtec
        #link: https://microtec.eu/sv-se
        #link_text: microtec.eu/sv-se
        sub_title: AI Intern
        caption: January 2023 - August 2023
        description: |
          Microtec develops intelligent wood scanners all over the world.
          As a member of the R&D team, my responsibilities included the development and implementation of machine learning solutions
          to extend the functionality of the wood scanners. I worked 8-10 hours per week during my studies and full-time during the summer.
    
      - layout: left
        title: Linköping University
        sub_title: Teaching assistant
        caption: 2020 - 2022
        description: |
          I worked as a teaching assistant in several courses at Linköping University.
          My responsibilities included holding lab sessions, grading assignments, and answering student questions.
          I found this to be a great way to deepen my understanding of the course material and to help others.

### Education Section ###
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Linköping University
        link: https://liu.se/utbildning/program/f7ksa
        link_text: Statistik och Dataanalys
        caption: 2019 - 2022
        sub_title: BSc Statistics and Data Analysis
        description: |
          I found this program to be the perfect start for my data science career.
          The program was a mix of established statistical methods, programming, mathematics, and machine learning.
          Most courses were divided into the lecture + lab + computer exam structure.
          I found this teaching technique to be very effective as it gives a deep understanding of the theory as well as practical skills.
          Many courses also contained a small project, allowing me to be creative and apply the learned methods to real data, something I enjoyed.

      - layout: left
        title: Linköping University
        link: https://liu.se/en/education/program/f7mml
        link_text: Statistics and Machine Learning
        caption: 2022 - 2024
        sub_title: MSc Statistics and Machine Learning
        description: |
          After the BSc program introduced me to the world of data science, I was eager to learn more.
          The program followed a similar structure as the BSc program, but with more advanced models and a deeper dive into the methods.
          This extended my toolbox to work with new data types and models. I will graduate in June 2024, thrilled to see what the future holds.

  - title: Extracurriculat activity
    layout: list
    content:
      - layout: left
        title: SCB
        sub_title: Student association
        caption: 2020 - 2021
        description: |
          Planned and organized festive arrangements such as party's and theme dinners with a special emphasis during the two-week introduction period.
          My main responsibilities was planning, ordering and preparing food for all events. As part of the group, I also took part in the overall planning of all activities.

### My interests Section ###
  - title: A little more about me 
    layout: text
    content: |
      ## **Programming languages**
      - Python
      - R
      - SQL
      - SAS
      - TypeScript

      ## **Tools**
      - Git
      - OpenAI API
      - Huggingface
      - Roboflow
      - Ollama
      - Langchain
      - PyTorch
      - TensorFlow
      - MiniTab
      - SPSS

      Thats it for now! If you want to know more about me, feel free to reach out to me on LinkedIn or send me an email.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
