# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Leonard Persson Norblad
title: MSs in Statistics and Machine Learning
email: leonard.norblad@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  leonnorblad
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: leonardnorblad
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0004-8562-4118

additional_links:
- title: Kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/leonnorblad

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# <i class="fa-brands fa-kaggle"></i>

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profilepic.jpg
about_content: | # this will include new lines to allow paragraphs
  Last year Master student in Statistics and machine learning.

  Skilled in <mark>Python</mark>,  <mark>R</mark> and <mark>SQL</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Claim Verification Using Generated Data by ChatGPT and Wikipedia
        link: https://github.com/Leonnorblad/fact-verification
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          As a part of the LiU text-mining course, I decided to dive deeper in the task of fact verification.
          The model I developed analyzes a user input string and predicts the truthfulness. This is performed by
          comparing the input string to a paragapth of *evidence*. To extract claims and evidence to train the model I
          scraped wikipedia pages and then fed the articles together with instructions to generate a claim to ChatGPT
          with the help of OpenAIs API. The Wikipedia articles could then be used as evidence and the output generated by
          the GPT model could be used as claims. I then enbedded the claims and evidence using BERT and trained the classification model.

      content:
      - layout: top-middle
        title: R Package "SeqAlignR"
        link: https://cran.r-project.org/web/packages/SeqAlignR/index.html
        link_text: CRAN page
        #additional_links:
        #  - title:  Github
        #    icon: fab fa-github
        #    url: https://github.com/Leonnorblad/SeqAlignR
        description: |
         As a part of the LiU course Bioinformatics, I developed an R package for sequence alignment and visualization. The package is available on CRAN and can be installed using the command `install.packages("SeqAlignR")`.


          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microtec
        link: https://microtec.eu/sv-se
        link_text: microtec.eu/sv-se
        sub_title: AI Intern
        caption: January 2023 - August 2023
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            As a part of the AI team, I developed deep learning solutions for wood scanners. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Linköping University
        caption: 2019 - 2022
        sub_title: BSc Statistics and Data Analysis
      #  quote: >
      #    Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I studied statistics and data analysis at Linköping University. I learned to use R, SQL, SAS, Minitab and SPSS to analyze and visualize data.
      - layout: left
        title: Linköping University
        caption: 2022 - 2024
        sub_title: MSc Statistics and Machine Learning
        description: | # this will include new lines to allow paragraphs
          I am currently studying statistics and machine learning at Linköping University.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I like to spend my freetime on Kaggle.com[kaggle].

      Look at this cool image  
      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
